# Generated by Django 2.0 on 2018-01-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='blog.Category', verbose_name='分类'),
        ),
    ]
